apiVersion: v1
kind: Service
metadata:
  name: db # we need to use this service name as worker as db hardcoded!!!
  labels:
{{ include "voting-app.labels" . | indent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "voting-app.db.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}