apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.worker.fullname" . }}
  labels:
{{ include "voting-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "voting-app.worker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "voting-app.worker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.worker.image.repository }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        name: {{ include "voting-app.worker.name" . }}