apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.vote.fullname" . }}
  labels:
{{ include "voting-app.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.vote.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "voting-app.vote.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "voting-app.vote.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "voting-app.vote.name" . }}
          image: "{{ .Values.vote.image.repository }}:{{ .Values.vote.image.tag }}"
          imagePullPolicy: {{ .Values.vote.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.vote.container.port }}
              protocol: TCP