# Vote app
vote:
  nameOverride: "vote"
  service:
    type: NodePort
    port: 5000
    nodePort: 31000
  replicaCount: 1
  image:
    repository: dockersamples/examplevotingapp_vote
    tag: before
    pullPolicy: IfNotPresent
  container:
    port: 80

# Redis
redis:
  nameOverride: "redis"
  replicaCount: 1
  image:
    repository: redis
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379

# Worker
worker:
  nameOverride: "worker"
  replicaCount: 1
  image:
    repository: dockersamples/examplevotingapp_worker
    pullPolicy: IfNotPresent

# Db
db:
  nameOverride: "db"
  replicaCount: 1
  image:
    repository: postgres
    tag: 9.4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432

# Result
result:
  nameOverride: "result"
  replicaCount: 1
  image:
    repository: dockersamples/examplevotingapp_result
    tag: before
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 5001
    targetPort: 80
    nodePort: 31001